server:
  port: 8001

spring:
  application:
    name: goods-provider
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/dbtable?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: 123456

mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.example.goodscommon.pojo
eureka:
  client:
#    fetch-registry: true
    service-url:
      defaultzone: http://localhost:8761/eureka
logging:
  level:
    com:
      example:
        goodsprovider:
          Dao: debug

